### ISSUE TITLE
New Template

### ISSUE THREAD

**Issue by mauricio-msp** [Yemachu/cardmaker#1]
Add the template for duel style skill cards with the new play mode.

**Comment by Yemachu** [comment]
Are you referring to [Skill cards](https://yugioh.fandom.com/wiki/Skill_Card)?

Either way, this would require a new border image where the content of the official card (name and effect) is no longer present. Finding a good image to use as a base, and removing said content will take some time.

**Comment by mauricio-msp** [comment]
https://www.google.com/search?q=template+skill+card&client=firefox-b-d&tbm=isch&source=iu&ictx=1&fir=DYDZdMXcUH9AVM%253A%252C3pM5QnPG3ENJVM%252C_&usg=AI4_-kQRHdto41xQFTmGcPy-Ji1FrmYn_A&sa=X&ved=2ahUKEwiW9biS2rngAhVwILkGHU3cDCcQ9QEwAXoECAUQBA&biw=1366&bih=664#imgrc=DYDZdMXcUH9AVM:
