### ISSUE TITLE
Link Rating Font

### ISSUE THREAD

**Issue by Germaniac** [Yemachu/cardmaker#2]
Hi, the font Konami uses for Link Rating number looks closer to IDroid than Audiowide, maybe you'd consider it.

https://www.dafont.com/idroid.font

**Comment by Germaniac** [comment]
You might also want to look at this

https://forum.yugiohcardmaker.net/topic/308603-fonts-for-yu-gi-oh-card-making-with-multilingual-support/

**Comment by Germaniac** [comment]
You might also want to look at this

https://forum.yugiohcardmaker.net/topic/308603-fonts-for-yu-gi-oh-card-making-with-multilingual-support/

**Comment by Yemachu** [comment]
IDroid might indeed be a closer match to the font used for Link cards compared to Audiowide. There are however a few reasons why I prefer using Audiowide. 

- Google Fonts has a convenient API for requesting different fonts.
- Making sure fonts show up correctly in different browsers has been taken care of.
- Caching allows fonts to load faster if the user has already visited another site which uses said font.
- Audiowide is an open source font, as far as I'm aware, so there are most likely less legal implications.

I could however make the cardmaker try to use IDroid, but not distribute it. This way it could use said font if the user has installed it on their device. This however foregoes some control over the appearance.

**Comment by Germaniac** [comment]
With the release of Link-6, IDroid doesn't seem to be the correct font anymore. This would be the correct font https://en.m.fontke.com/font/26389414/
